// <auto-generated />

#nullable disable

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Pulse.Infra.Database.Contexts;

namespace Pulse.Infra.Database.Migrations.Sqlite
{
    [DbContext(typeof(SqliteDatabaseContext))]
    [Migration("20260525143117_User")]
    partial class User
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Pulse.Domain.Aggregates.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("security_stamp");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0u)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.Users.User", b =>
                {
                    b.OwnsOne("Pulse.Domain.Aggregates.Users.ValueObjects.EmailAddress", "EmailAddress", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("TEXT")
                                .HasColumnName("id");

                            b1.Property<bool>("IsConfirmed")
                                .HasColumnType("INTEGER")
                                .HasColumnName("email_confirmed");

                            b1.Property<string>("NormalizedValue")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("normalized_email");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.HasIndex("NormalizedValue")
                                .IsUnique()
                                .HasDatabaseName("ix_users_normalized_email");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.OwnsOne("Pulse.Domain.Aggregates.Users.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("TEXT")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("last_name");

                            b1.Property<string>("NormalizedName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("normalized_name");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.OwnsOne("Pulse.Domain.Aggregates.Users.ValueObjects.Username", "Username", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("TEXT")
                                .HasColumnName("id");

                            b1.Property<string>("NormalizedValue")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("normalized_username");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("username");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_users_username");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("EmailAddress");

                    b.Navigation("Name");

                    b.Navigation("Username")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
