<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>Nomanova.Pulse.Plugin</PackageId>
        <Version>0.0.1</Version>
        <Authors>NOMANOVA</Authors>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\domain\Pulse.Domain.Channels\Pulse.Domain.Channels.csproj" />
    </ItemGroup>
    
</Project>
