###
### Add
###
POST {{root}}/api/ctrl/v1/applications/add
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "organizationId": "{{orgId}}",
  "applicationName": "{{appName}}"
}

###
### Remove
###
POST {{root}}/api/ctrl/v1/applications/remove
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "applicationId": "{{appId}}"
}

###
### Fetch
###
POST {{root}}/api/ctrl/v1/applications/fetch
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "applicationId": "{{appId}}"
}

###
### Search
###
POST {{root}}/api/ctrl/v1/applications/search
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "query": null,
  "lastId": null,
  "pageSize": null,
  "ascending": true,
  "orderBy": null,
  "organizationId": "{{orgId}}"
}
