###
### Add
###
POST {{root}}/api/ctrl/v1/connections/add
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "environmentId": "{{envId}}",
  "pluginId": "com.nomanova.pulse.plugin.provider.email.console",
  "parameters": {
    "from-email": "info@nomanova.com",
    "from-name": ""
  }
}

###
### Remove
###
POST {{root}}/api/ctrl/v1/connections/remove
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "connectionId": "{{conId}}"
}