###
### Add (Email - Console)
###
POST {{root}}/api/ctrl/v1/connections/add
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "environmentId": "{{envId}}",
  "pluginId": "com.nomanova.pulse.plugin.provider.email.console",
  "parameters": {}
}

###
### Add (Email - SendGrid)
###
POST {{root}}/api/ctrl/v1/connections/add
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "environmentId": "{{envId}}",
  "pluginId": "com.nomanova.pulse.plugin.provider.email.sendgrid",
  "parameters": {
    "apiKey": "{{sendGridApiKey}}"
  }
}

###
### Remove
###
POST {{root}}/api/ctrl/v1/connections/remove
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "connectionId": "{{conId}}"
}