###
### Add (Email - Console)
###
POST {{root}}/api/ctrl/v1/connections/add
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "environmentId": "{{envId}}",
  "pluginId": "com.nomanova.pulse.plugin.provider.email.console",
  "parameters": {}
}

###
### Add (Email - SendGrid)
###
POST {{root}}/api/ctrl/v1/connections/add
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "environmentId": "{{envId}}",
  "pluginId": "com.nomanova.pulse.plugin.provider.email.sendgrid",
  "parameters": {
    "apiKey": "{{sendGridApiKey}}"
  }
}

###
### Add (SMS - Console)
###
POST {{root}}/api/ctrl/v1/connections/add
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "environmentId": "{{envId}}",
  "pluginId": "com.nomanova.pulse.plugin.provider.sms.console",
  "parameters": {}
}

###
### Fetch
###
POST {{root}}/api/ctrl/v1/connections/fetch
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "connectionId": "3gqjyyhe7chfklwvvmabi21sk"
}

###
### Search
###
POST {{root}}/api/ctrl/v1/connections/search
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "lastId": null,
  "pageSize": null,
  "ascending": true,
  "environmentId": "{{envId}}",
  "status": null
}

###
### Remove
###
POST {{root}}/api/ctrl/v1/connections/remove
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "connectionId": "{{conId}}"
}