###
### Add
###
POST {{root}}/api/ctrl/v1/environments/add
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "applicationId": "{{appId}}",
  "environmentName": "{{envName}}"
}

###
### Remove
###
POST {{root}}/api/ctrl/v1/environments/remove
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "environmentId": "{{envId}}"
}

###
### Fetch
###
POST {{root}}/api/ctrl/v1/environments/fetch
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "environmentId": "{{envId}}"
}

###
### Search
###
POST {{root}}/api/ctrl/v1/environments/search
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "query": null,
  "lastId": null,
  "pageSize": null,
  "ascending": true,
  "orderBy": null,
  "applicationId": "{{appId}}"
}
