### Create
POST {{root}}/api/ctrl/v1/environments/create
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "organizationName": "{{organizationName}}",
  "applicationName": "{{applicationName}}",
  "name": "Production"
}
