###
### Add
###
POST {{root}}/api/ctrl/v1/organizations/add
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "organizationName": "{{organizationName}}"
}

###
### Remove
###
POST {{root}}/api/ctrl/v1/organizations/remove
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "organizationId": "{{orgId}}"
}

###
### Fetch
###
POST {{root}}/api/ctrl/v1/organizations/fetch
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "organizationId": "{{orgId}}"
}

###
### Search
###
POST {{root}}/api/ctrl/v1/organizations/search
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "query": null,
  "lastId": null,
  "pageSize": null,
  "ascending": true,
  "orderBy": null
}