###
### Add
###
POST {{root}}/api/data/v1/workflows/add
Content-Type: application/json
X-Api-Key: {{apiKey}}

{
  "environmentId": "{{envId}}",
  "workflowName": "{{wrkName}}"
}

###
### Remove
###
POST {{root}}/api/data/v1/workflows/remove
Content-Type: application/json
X-Api-Key: {{apiKey}}

{
  "workflowId": "{{wrkId}}"
}

###
### Fetch
###
POST {{root}}/api/data/v1/workflows/fetch
Content-Type: application/json
X-Api-Key: {{apiKey}}

{
  "workflowId": "{{wrkId}}"
}

###
### Search
###
POST {{root}}/api/data/v1/workflows/search
Content-Type: application/json
X-Api-Key: {{apiKey}}

{
  "query": null,
  "lastId": null,
  "pageSize": null,
  "ascending": true,
  "orderBy": null,
  "environmentId": "{{envId}}"
}

###
### Publish
###
POST {{root}}/api/data/v1/workflows/publish
Content-Type: application/json
X-Api-Key: {{apiKey}}

{
  "workflowId": "{{wrkId}}"
}

###
### Fetch Version
###
POST {{root}}/api/data/v1/workflows/versions/fetch
Content-Type: application/json
X-Api-Key: {{apiKey}}

{
  "workflowVersionId": "v4vcm4tppn5e07ynh1iuwcin"
}

###
### Search Versions
###
POST {{root}}/api/data/v1/workflows/versions/search
Content-Type: application/json
X-Api-Key: {{apiKey}}

{
  "lastId": null,
  "pageSize": null,
  "ascending": true,
  "workflowId": "{{wrkId}}",
  "status": null
}

###
### Add Version Step
###
POST {{root}}/api/data/v1/workflows/versions/add-step
Content-Type: application/json
X-Api-Key: {{apiKey}}

{
  "workflowId": "{{wrkId}}",
  "workflowVersionId": "v4vcm4tppn5e07ynh1iuwcin"
}

###
### Remove Version Step
###
POST {{root}}/api/data/v1/workflows/versions/remove-step
Content-Type: application/json
X-Api-Key: {{apiKey}}

{
  "workflowId": "{{wrkId}}",
  "workflowVersionId": "v4vcm4tppn5e07ynh1iuwcin",
  "workflowVersionStepId": "1iol8861kviiq1rrmioqdwfg1"
}