// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pulse.Infra.Database.Contexts;

#nullable disable

namespace Pulse.Infra.Database.Migrations.Postgres
{
    [DbContext(typeof(PostgresDatabaseContext))]
    [Migration("20260720145807_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pulse.Domain.Aggregates.Applications.Application", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_applications");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_applications_organization_id");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.Environments.Environment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_environments");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_environments_application_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_environments_organization_id");

                    b.ToTable("environments", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.Memberships.Membership", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EnvironmentId")
                        .HasColumnType("text")
                        .HasColumnName("environment_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("text")
                        .HasColumnName("organization_id");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_memberships");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_memberships_application_id");

                    b.HasIndex("EnvironmentId")
                        .HasDatabaseName("ix_memberships_environment_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_memberships_organization_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_memberships_role_id");

                    b.HasIndex("UserId", "OrganizationId", "ApplicationId", "EnvironmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_memberships_user_id_organization_id_application_id_environm");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.Organizations.Organization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.Roles.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_built_in");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.WorkflowInstances.Entities.WorkflowInstanceStep", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<long>("Order")
                        .HasColumnType("bigint")
                        .HasColumnName("order");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("WorkflowInstanceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workflow_instance_id");

                    b.Property<string>("WorkflowVersionStepId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workflow_version_step_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_instance_steps");

                    b.HasIndex("WorkflowVersionStepId")
                        .HasDatabaseName("ix_workflow_instance_steps_workflow_version_step_id");

                    b.HasIndex("WorkflowInstanceId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_instance_steps_workflow_instance_id_order");

                    b.ToTable("workflow_instance_steps", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.WorkflowInstances.WorkflowInstance", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("environment_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workflow_id");

                    b.Property<string>("WorkflowVersionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workflow_version_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_instances");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_workflow_instances_application_id");

                    b.HasIndex("EnvironmentId")
                        .HasDatabaseName("ix_workflow_instances_environment_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_workflow_instances_organization_id");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("ix_workflow_instances_workflow_id");

                    b.HasIndex("WorkflowVersionId")
                        .HasDatabaseName("ix_workflow_instances_workflow_version_id");

                    b.ToTable("workflow_instances", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.Workflows.Entities.WorkflowVersion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_versions");

                    b.HasIndex("WorkflowId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_versions_workflow_id_version");

                    b.ToTable("workflow_versions", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.Workflows.Entities.WorkflowVersionStep", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<long>("Order")
                        .HasColumnType("bigint")
                        .HasColumnName("order");

                    b.Property<string>("WorkflowVersionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workflow_version_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_version_steps");

                    b.HasIndex("WorkflowVersionId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_version_steps_workflow_version_id_order");

                    b.ToTable("workflow_version_steps", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.Workflows.Workflow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EnvironmentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("environment_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization_id");

                    b.Property<string>("PublishedVersionId")
                        .HasColumnType("text")
                        .HasColumnName("published_version_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_workflows");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_workflows_application_id");

                    b.HasIndex("EnvironmentId")
                        .HasDatabaseName("ix_workflows_environment_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_workflows_organization_id");

                    b.ToTable("workflows", (string)null);
                });

            modelBuilder.Entity("Pulse.Infra.Database.Messaging.Inbox.InboxMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Handler")
                        .HasColumnType("text")
                        .HasColumnName("handler");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on");

                    b.Property<DateTime>("ReceivedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_on");

                    b.HasKey("Id", "Handler")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ProcessedOn")
                        .HasDatabaseName("ix_inbox_messages_processed_on");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Pulse.Infra.Database.Messaging.Outbox.OutboxMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on");

                    b.Property<string>("ProcessingId")
                        .HasColumnType("text")
                        .HasColumnName("processing_id");

                    b.Property<DateTime?>("ProcessingOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_on");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredOn")
                        .HasDatabaseName("ix_outbox_messages_occurred_on")
                        .HasFilter("processed_on IS NULL");

                    b.HasIndex("ProcessedOn")
                        .HasDatabaseName("ix_outbox_messages_processed_on")
                        .HasFilter("processed_on IS NOT NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.Applications.Application", b =>
                {
                    b.HasOne("Pulse.Domain.Aggregates.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_applications_organizations_organization_id");

                    b.OwnsOne("Pulse.Domain.Common.Models.ValueObjects.ObjectName", "Name", b1 =>
                        {
                            b1.Property<string>("ApplicationId")
                                .HasColumnType("text")
                                .HasColumnName("id");

                            b1.Property<string>("NormalizedValue")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("normalized_name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.HasKey("ApplicationId");

                            b1.ToTable("applications");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId")
                                .HasConstraintName("fk_applications_applications_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.Environments.Environment", b =>
                {
                    b.HasOne("Pulse.Domain.Aggregates.Applications.Application", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_environments_applications_application_id");

                    b.HasOne("Pulse.Domain.Aggregates.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_environments_organizations_organization_id");

                    b.OwnsOne("Pulse.Domain.Common.Models.ValueObjects.ObjectName", "Name", b1 =>
                        {
                            b1.Property<string>("EnvironmentId")
                                .HasColumnType("text")
                                .HasColumnName("id");

                            b1.Property<string>("NormalizedValue")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("normalized_name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.HasKey("EnvironmentId");

                            b1.ToTable("environments");

                            b1.WithOwner()
                                .HasForeignKey("EnvironmentId")
                                .HasConstraintName("fk_environments_environments_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.Memberships.Membership", b =>
                {
                    b.HasOne("Pulse.Domain.Aggregates.Applications.Application", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("fk_memberships_applications_application_id");

                    b.HasOne("Pulse.Domain.Aggregates.Environments.Environment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .HasConstraintName("fk_memberships_environments_environment_id");

                    b.HasOne("Pulse.Domain.Aggregates.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("fk_memberships_organizations_organization_id");

                    b.HasOne("Pulse.Domain.Aggregates.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_roles_role_id");

                    b.HasOne("Pulse.Domain.Aggregates.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_users_user_id");
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.Organizations.Organization", b =>
                {
                    b.OwnsOne("Pulse.Domain.Common.Models.ValueObjects.ObjectName", "Name", b1 =>
                        {
                            b1.Property<string>("OrganizationId")
                                .HasColumnType("text")
                                .HasColumnName("id");

                            b1.Property<string>("NormalizedValue")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("normalized_name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.HasKey("OrganizationId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_organizations_name");

                            b1.ToTable("organizations");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId")
                                .HasConstraintName("fk_organizations_organizations_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.Roles.Role", b =>
                {
                    b.OwnsOne("Pulse.Domain.Common.Models.ValueObjects.ObjectName", "Name", b1 =>
                        {
                            b1.Property<string>("RoleId")
                                .HasColumnType("text")
                                .HasColumnName("id");

                            b1.Property<string>("NormalizedValue")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("normalized_name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.HasKey("RoleId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_roles_name");

                            b1.ToTable("roles");

                            b1.WithOwner()
                                .HasForeignKey("RoleId")
                                .HasConstraintName("fk_roles_roles_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.Users.User", b =>
                {
                    b.OwnsOne("Pulse.Domain.Common.Models.ValueObjects.ObjectName", "Username", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("text")
                                .HasColumnName("id");

                            b1.Property<string>("NormalizedValue")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("normalized_username");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("username");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_users_username");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.OwnsOne("Pulse.Domain.Aggregates.Users.ValueObjects.EmailAddress", "EmailAddress", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("text")
                                .HasColumnName("id");

                            b1.Property<bool>("IsConfirmed")
                                .HasColumnType("boolean")
                                .HasColumnName("email_confirmed");

                            b1.Property<string>("NormalizedValue")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("normalized_email");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.HasIndex("NormalizedValue")
                                .IsUnique()
                                .HasDatabaseName("ix_users_normalized_email");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.OwnsOne("Pulse.Domain.Aggregates.Users.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("text")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_name");

                            b1.Property<string>("NormalizedName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("normalized_name");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("EmailAddress");

                    b.Navigation("Name");

                    b.Navigation("Username")
                        .IsRequired();
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.WorkflowInstances.Entities.WorkflowInstanceStep", b =>
                {
                    b.HasOne("Pulse.Domain.Aggregates.WorkflowInstances.WorkflowInstance", null)
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_instance_steps_workflow_instances_workflow_instanc");

                    b.HasOne("Pulse.Domain.Aggregates.Workflows.Entities.WorkflowVersionStep", null)
                        .WithMany()
                        .HasForeignKey("WorkflowVersionStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_instance_steps_workflow_version_steps_workflow_ver");
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.WorkflowInstances.WorkflowInstance", b =>
                {
                    b.HasOne("Pulse.Domain.Aggregates.Applications.Application", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_instances_applications_application_id");

                    b.HasOne("Pulse.Domain.Aggregates.Environments.Environment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_instances_environments_environment_id");

                    b.HasOne("Pulse.Domain.Aggregates.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_instances_organizations_organization_id");

                    b.HasOne("Pulse.Domain.Aggregates.Workflows.Workflow", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_instances_workflows_workflow_id");

                    b.HasOne("Pulse.Domain.Aggregates.Workflows.Entities.WorkflowVersion", null)
                        .WithMany()
                        .HasForeignKey("WorkflowVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_instances_workflow_versions_workflow_version_id");
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.Workflows.Entities.WorkflowVersion", b =>
                {
                    b.HasOne("Pulse.Domain.Aggregates.Workflows.Workflow", null)
                        .WithMany("Versions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_versions_workflows_workflow_id");
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.Workflows.Entities.WorkflowVersionStep", b =>
                {
                    b.HasOne("Pulse.Domain.Aggregates.Workflows.Entities.WorkflowVersion", null)
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_version_steps_workflow_versions_workflow_version_id");
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.Workflows.Workflow", b =>
                {
                    b.HasOne("Pulse.Domain.Aggregates.Applications.Application", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflows_applications_application_id");

                    b.HasOne("Pulse.Domain.Aggregates.Environments.Environment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflows_environments_environment_id");

                    b.HasOne("Pulse.Domain.Aggregates.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflows_organizations_organization_id");

                    b.OwnsOne("Pulse.Domain.Common.Models.ValueObjects.ObjectName", "Name", b1 =>
                        {
                            b1.Property<string>("WorkflowId")
                                .HasColumnType("text")
                                .HasColumnName("id");

                            b1.Property<string>("NormalizedValue")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("normalized_name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.HasKey("WorkflowId");

                            b1.ToTable("workflows");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowId")
                                .HasConstraintName("fk_workflows_workflows_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.WorkflowInstances.WorkflowInstance", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.Workflows.Entities.WorkflowVersion", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Pulse.Domain.Aggregates.Workflows.Workflow", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
