<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <AssemblyName>Pulse.Web</AssemblyName>
        <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <DebugType>portable</DebugType>
        <DebugSymbols>true</DebugSymbols>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.12" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.0" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="10.0.11" />
        <PackageReference Include="MudBlazor" Version="9.9.0" />
        <PackageReference Include="CodeBeam.MudBlazor.Extensions" Version="9.1.0" />
        <PackageReference Include="MudBlazor.FontIcons.MaterialSymbols" Version="1.5.0" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Pulse.Web.Core\Pulse.Web.Core.csproj" />
    </ItemGroup>

    <!-- Run npm install before restore if node_modules is missing -->
    <Target Name="NpmInstall" BeforeTargets="Build" Condition="!Exists('node_modules')">
        <Exec Command="npm install" WorkingDirectory="$(MSBuildProjectDirectory)" />
    </Target>

    <!-- Compile Tailwind CSS before project build -->
    <Target Name="BuildTailwind" BeforeTargets="BeforeBuild">
        <Exec Command="npm run build:css" WorkingDirectory="$(MSBuildProjectDirectory)" />
    </Target>

</Project>
