<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Humanizer" Version="3.0.10" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Pulse.Api.Ctrl.Client\Pulse.Api.Ctrl.Client.csproj" />
      <ProjectReference Include="..\Pulse.Api.Ctrl.Contract\Pulse.Api.Ctrl.Contract.csproj" />
      <ProjectReference Include="..\Pulse.Api.Data.Client\Pulse.Api.Data.Client.csproj" />
      <ProjectReference Include="..\Pulse.Api.Data.Contract\Pulse.Api.Data.Contract.csproj" />
    </ItemGroup>

</Project>
